/**
 * Domain Types - File Artifacts
 *
 * Types for files sent from troise-ai to web clients.
 * Aligns with troise-ai WebSocket protocol for file delivery.
 */

/**
 * Source of the file artifact - determines confidence level
 * - tool: Generated by tool execution (confidence: 1.0)
 * - llm_extraction: Extracted by LLM from conversation (confidence: 0.8)
 * - regex: Extracted via pattern matching (confidence: 0.5)
 */
export type FileSource = "tool" | "llm_extraction" | "regex";

/**
 * Raw file data received from troise-ai WebSocket
 */
export interface IncomingFile {
  filename: string;
  base64Data: string;
  source: FileSource;
  confidence: number;
  filepath?: string;
  mimeType?: string;
}

/**
 * Decoded file ready for display/download
 */
export interface DecodedFile {
  filename: string;
  blob: Blob;
  url: string;  // Object URL for download/preview
  source: FileSource;
  confidence: number;
  filepath?: string;
}

/**
 * File suggestion requiring user confirmation before accepting
 */
export interface FileSuggestion extends IncomingFile {
  suggested: true;
}
